site_name: CHAUVET Pro Documentation
site_url: http://www.Chauvetlighting.com

theme:
  name: material
  custom_dir: overrides  # Keep this for future customizations
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  features:
    - content.code.copy

  icon:
    admonition:
      Useful_Information: material/file-edit
      success: material/menu

plugins:
  - search
  - glightbox
  - mermaid2
  - table-reader:
      data_path: "docs/products"

extra:
  generator: false

markdown_extensions:
  - attr_list
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - "."
        - "docs"
        - "src"
      restrict_base_path: false
      check_paths: true
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences



extra_javascript:
  - https://cdn.jsdelivr.net/npm/three@0.150.1/build/three.min.js
  - https://cdn.jsdelivr.net/npm/three@0.150.1/examples/js/loaders/GLTFLoader.js
  - https://cdn.jsdelivr.net/npm/three@0.150.1/examples/js/controls/OrbitControls.js
  - https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js
  - javascripts/three-model-viewer.js
  - javascripts/model-viewer.js
  - javascripts/pdf-export.js
  - https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js # Add this


extra_css:
  - stylesheets/extra.css

copyright: "© 2025 Chauvet Lighting"